// src/components/Adsense.vue
<template>
  <ins
      class="adsbygoogle"
      :class="adClass"
      :style="adStyle"
      :data-ad-client="adClient"
      :data-ad-slot="adSlot"
      :data-ad-format="adFormat"
      :data-full-width-responsive="adResponsive"
  />
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'

@Component({
  name: 'Adsense',
})
export default class Adsense extends Vue {
  @Prop() adSlot!: string
  @Prop() adClass!: string
  private readonly adStyle!: string
  private readonly adClient!: string
  private readonly adFormat!: string
  private readonly adResponsive!: string

  constructor() {
    super()
    this.adStyle = 'display: block'
    this.adClient = 'ca-pub-7791595479585064'
    this.adFormat = 'auto'
    this.adResponsive = 'true'
  }

  mounted(): void {
    this.showAd()
  }

  showAd(): void {
    this.$nextTick(() => {
      try {
        (window.adsbygoogle = window.adsbygoogle || []).push({})
      } catch (e) {
        console.error(e)
      }
    })
  }
}
</script>

// src/components/adsense/index.tsx
import React from 'react'
import { useEffect } from 'react'

export const Adsense: React.FC = () => {
  useEffect(() => {
    // @ts-ignore
    (window['adsbygoogle'] = window?.adsbygoogle || []).push({})
  })

  return (
    <div style={{ padding: 8 }}>
      <ins className="adsbygoogle"
           style={{ display: 'block' }}
           data-ad-client={'ca-pub-7596204383080174'}
           data-ad-slot={'8308888794'}
           data-ad-format="auto"
           data-full-width-responsive="true"/>
    </div>
  )
}
