// src/layouts/Header.vue
<template>
  <header class="header" :class="{ 'hidden': !show }">
    <g-link to="/"><h1>🐋 {{siteName}}</h1></g-link>
    <ClientOnly>
      <ThemeToggle/>
    </ClientOnly>
  </header>
</template>

<script lang="ts">
  import { Component, Prop, Vue } from 'vue-property-decorator'
  import ThemeToggle from '../components/ThemeToggle.vue'

  @Component({
    name: 'Header',
    components: {
      ThemeToggle,
    },
  })
  export default class Header extends Vue {
    @Prop() siteName!: string
    @Prop() show!: boolean

    constructor() {
      super()
    }
  }
</script>

<style lang="scss">
  header {
    background-color: var(--app-header-color);
    display: flex;
    align-items: center;
    justify-content: space-between;
    position: fixed;
    height: 6.5rem;
    padding: 0 5%;
    top: 0;
    left: 0;
    right: 0;
    border-bottom: 1px solid rgba(0, 0, 0, 0.07);
    box-shadow: 0 3px 5px 0 rgba(0, 0, 0, 0.05);
    z-index: 50;
    transition: top 0.2s ease-in-out;

    h1 {
      font-size: 2.2rem;
      font-family: Gugi;
      color: var(--app-font-color);
      font-weight: bold;
    }
  }

  .hidden {
    height: 0;
    transition: height 0.2s ease-in-out;

    > * {
      display: none;
    }
  }

  @media only screen and (max-width: 500px) {
    .header {
      h1 {
        font-size: 2rem;
      }
    }
  }
</style>

// src/components/header/index.tsx
import { Menu, ThemeToggle } from '@components'
import { HeaderQueryResponse } from '@constant'
import { graphql, Link, useStaticQuery } from 'gatsby'
import React from 'react'
import styled from 'styled-components'

const HeadDiv = styled.header`
  width: 100%;
  background-color: var(--app-header-bg-color);
  z-index: 32;
  align-items: center;
  display: flex;
  flex-wrap: nowrap;
  padding: 0.75rem 1.5rem 0.5rem;
  box-shadow: 0 3px 5px 0 var(--app-header-border-color);
  justify-content: space-between;
  position: fixed;
  transition: opacity 0.1s ease-out;
  opacity: 0.77;
  backdrop-filter: blur(22px);

  @media only screen and (max-width: 768px) {
  }
`

const HeadRight = styled.span`
  display: inherit;
`

const HeadLeft = styled.span`
  h1 {
    color: #cdd9e5;
    font-size: 13.5px;
    font-weight: 200;
  }
`

export const Header: React.FC = () => {
  const { site: { siteMetadata } } = useStaticQuery<HeaderQueryResponse>(headerQuery)
  return (
    <HeadDiv>
      <HeadLeft>
        <Link to={'/'}>
          <h1>{siteMetadata.site_name}</h1>
        </Link>
      </HeadLeft>
      <HeadRight>
        <ThemeToggle/>
        {/*<Menu/>*/}
      </HeadRight>
    </HeadDiv>
  )
}

const headerQuery = graphql`
  query HeaderQuery { 
    site { 
      siteMetadata { 
        site_name 
      }
    }
  } 
`
