// src/components/comment/index.tsx
import { THEME_MODE, UT_THEME } from '@constant'
import { getTheme } from '@utils/storage'
import React, { createRef, RefObject, useEffect } from 'react'

interface CommentProps {
  repo: string
}

interface UtterancesConfig {
  src: string
  type: string
  repo: string
  theme: UT_THEME
  async: boolean
  'issue-term': string
  label: string
  crossorigin: 'anonymous'
}

const LABEL = '🗣:speech_balloon:'

export const Comment: React.FC<CommentProps> = ({ repo }) => {
  const commentRef: RefObject<HTMLSpanElement> = createRef()
  const mode = getTheme() ? THEME_MODE.DARK : THEME_MODE.LIGHT

  const config: UtterancesConfig = {
    src: 'https://utteranc.es/client.js',
    type: 'text/javascript',
    repo,
    theme: mode === THEME_MODE.DARK ? UT_THEME.DARK : UT_THEME.LIGHT,
    async: true,
    'issue-term': 'comment',
    label: LABEL,
    crossorigin: 'anonymous'
  }

  useEffect(() => {
    const curComment = commentRef.current!.firstChild
    if (curComment) {
      commentRef.current!.removeChild(curComment)
    }

    const utterances = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      utterances.setAttribute(key, value)
    })
    commentRef.current!.appendChild(utterances)
  }, [])

  return (
    <span id="comment" ref={commentRef}/>
  )
}

// src/components/Comment.vue
<template>
  <div id="comment"></div>
</template>

<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator'

  @Component({
    name: 'Comment',
  })
  export default class Comment extends Vue {
    constructor() {
      super()
    }

    mounted(): void {
      const utterances = document.createElement('script')
      utterances.type = 'text/javascript'
      utterances.async = true
      utterances.crossOrigin = 'anonymous'
      utterances.src = 'https://utteranc.es/client.js'

      const mode = localStorage.getItem('theme')

      utterances.setAttribute('theme', mode === 'dark' ? 'dark-blue' : 'github-light')
      utterances.setAttribute('issue-term', 'url')
      utterances.setAttribute('label', '🗣:speech_balloon:')
      utterances.setAttribute('repo', 'akasai/akasai.github.io')
      document.getElementById('comment')?.appendChild(utterances);
    }
  }
</script>

<style lang="scss">
  #comment {
    width: 100%;
  }
</style>
